### ISSUE TITLE
Bug with fitting the model

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#24] opened 2023-04-17 13:32 UTC
For the attached renewal rates dataset named "times" and the isotope dataset named "isotopes", I receive the attached message named "Bug OsteoBioR" when I try to fit the model.
[Isotopes.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/11249397/Isotopes.xlsx)
[Times.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/11249398/Times.xlsx)
![Bug OsteoBioR](https://user-images.githubusercontent.com/101706974/232466775-d9ac785a-5792-41f8-b84a-447e5200f585.PNG)

As Time variable(s): I click on "start" and "end"
As Element variables: I tick on every section. 
Individual variable: I tick on "ind"

By the error message it is not clear where the issue in the dataset is. However, I think the issue is a bug because I used the same dataset format that I was using in the past when the model was running fine. I also checked this by fitting the model for some past datasets that worked but I still receive the same message.

@arunge

**Comment by isomemo** [comment] 2023-04-24 16:20
@arunge any progress on this? Carlo has to use the tool for a project.

**Comment by arunge** [comment] 2023-04-25 18:12
Sorry, I was busy in another project. I could reproduce the issue and will check tomorrow what is going on here. Thanks for your patience!

**Comment by arunge** [comment] 2023-04-26 14:37
@CarloCocozza I prepared a [fix](https://github.com/Pandora-IsoMemo/osteo-bior/pull/25) for the problem that you mentioned above. Since the fix touches logic that was introduced with the new feature to add optional uncertainty for renewal rates I asked @mgross to review the code before it will go online.

However, if you need the fix very urgent, I can push the changes and ask @mgross to check the code afterwards.
Please let me know which is best for you.

**Comment by arunge** [comment] 2023-05-16 11:08
@CarloCocozza I finally merged the fix yesterday. However, the deployment failed for some reason, that is the [new version 23.04.01](https://github.com/Pandora-IsoMemo/osteo-bior/pull/25) was not available online yet. Now, checks passed and the [new version](https://github.com/Pandora-IsoMemo/osteo-bior/pull/25) is available on [OsteoBioR beta](https://isomemoapp.com/app/osteo-bio-r-beta).

Also today, @mgross replied and confirmed that the changes look fine.

Please let me know if there are more issues! Thanks for your patience!

**Closed by arunge** 2023-05-16 11:08 UTC
Labels: bug, OsteoBioR App

**Comment by CarloCocozza** [comment] 2023-05-16 12:38
@arunge Thanks!

Unfortunately the beta version crashes as soon as I upload a file for the renewal rates.

**Comment by arunge** [comment] 2023-05-16 12:54
Ok, I checked it and could not reproduce locally but online the app crashed. I will check what is going on!

**Comment by arunge** [comment] 2023-05-16 15:14
@CarloCocozza Now it also should work [online](https://isomemoapp.com/app/osteo-bio-r-beta):

![image](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/de9519bf-6b9d-48be-bac2-7351dfae532d)

**Comment by CarloCocozza** [comment] 2023-05-16 15:17
@arunge I immediately checked, but now it crashes when I fit the model and run.

**Comment by arunge** [comment] 2023-05-17 09:13
@CarloCocozza Now also running the model should work on [osteobior beta](https://isomemoapp.com/app/osteo-bio-r-beta). Sorry for the trouble!

![image](https://github.com/Pandora-IsoMemo/osteo-bior/assets/16759098/ffee98a0-9f0b-4b7a-bbf3-66f6b7fd1388)

**Comment by CarloCocozza** [comment] 2023-05-17 12:54
@arunge 
Thanks! I am using it and it seems to work fine.
